//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Windows.Forms;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace Company.CyberPhisical_final
{
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	/// <remarks>
	/// Double-derived class to allow easier code customization.
	/// </remarks>
	public partial class CyberPhisical_finalToolboxHelper : CyberPhisical_finalToolboxHelperBase 
	{
		/// <summary>
		/// Constructs a new CyberPhisical_finalToolboxHelper.
		/// </summary>
		public CyberPhisical_finalToolboxHelper(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider) { }
	}
	
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Justification = "The store is disposed on domain shut down")]
	public abstract class CyberPhisical_finalToolboxHelperBase
	{
		/// <summary>
		/// Toolbox item filter string used to identify CyberPhisical_final toolbox items.  
		/// </summary>
		/// <remarks>
		/// See the MSDN documentation for the ToolboxItemFilterAttribute class for more information on toolbox
		/// item filters.
		/// </remarks>
		public const string ToolboxFilterString = "CyberPhisical_final.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify ConnectionTool1 connector tool.
		/// </summary>
		public const string ConnectionTool1FilterString = "ConnectionTool1.1.0";

	
		private global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem> toolboxItemCache = new global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem>();
		private DslModeling::Store toolboxStore;
		
		private global::System.IServiceProvider sp;
		
		/// <summary>
		/// Constructs a new CyberPhisical_finalToolboxHelperBase.
		/// </summary>
		protected CyberPhisical_finalToolboxHelperBase(global::System.IServiceProvider serviceProvider)
		{
			if(serviceProvider == null) throw new global::System.ArgumentNullException("serviceProvider");
			
			this.sp = serviceProvider;
		}
		
		/// <summary>
		/// Serivce provider used to access services from the hosting environment.
		/// </summary>
		protected global::System.IServiceProvider ServiceProvider
		{
			get
			{
				return this.sp;
			}
		}

		/// <summary>
		/// Returns the display name of the tab that should be opened by default when the editor is opened.
		/// </summary>
		public static string DefaultToolboxTabName
		{
			get
			{
				return global::Company.CyberPhisical_final.CyberPhisical_finalDomainModel.SingletonResourceManager.GetString("CyberPhisical_finalToolboxTab", global::System.Globalization.CultureInfo.CurrentUICulture);
			}
		}
		
		
		/// <summary>
		/// Returns the toolbox items count in the default tool box tab.
		/// </summary>
		public static int DefaultToolboxTabToolboxItemsCount
		{
			get
			{
				return 11;
			}
		}
		

		/// <summary>
		/// Returns a list of custom toolbox items to be added dynamically
		/// </summary>
		public virtual global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem> toolboxItems = new global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem>();
			return toolboxItems;
		}
		
		/// <summary>
		/// Creates an ElementGroupPrototype for the element tool corresponding to the given domain class id.
		/// Default behavior is to create a prototype containing an instance of the domain class.
		/// Derived classes may override this to add additional information to the prototype.
		/// </summary>
		protected virtual DslModeling::ElementGroupPrototype CreateElementToolPrototype(DslModeling::Store store, global::System.Guid domainClassId)
		{
			DslModeling::ModelElement element = store.ElementFactory.CreateElement(domainClassId);
			DslModeling::ElementGroup elementGroup = new DslModeling::ElementGroup(store.DefaultPartition);
			elementGroup.AddGraph(element, true);
			return elementGroup.CreatePrototype();
		}

		/// <summary>
		/// Returns instance of ModelingToolboxItem based on specified name.
		/// This method must be called from within a Transaction. Failure to do so will result in an exception
		/// </summary>
		/// <param name="itemId">unique name of desired ToolboxItem</param>
		/// <param name="store">Store to perform the operation against</param>
		/// <returns>An instance of ModelingToolboxItem if the itemId can be resolved, null otherwise</returns>
		public virtual DslDesign::ModelingToolboxItem GetToolboxItem(string itemId, DslModeling::Store store)
		{
			DslDesign::ModelingToolboxItem result = null;
			if (string.IsNullOrEmpty(itemId))
			{
				return null;
			}
			if (store == null)
			{
				return null;
			}
			global::System.Resources.ResourceManager resourceManager = global::Company.CyberPhisical_final.CyberPhisical_finalDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;
			switch(itemId)
			{
				case "Company.CyberPhisical_final.DeviceToolboxItem":
					// Add Device shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.CyberPhisical_final.DeviceToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("DeviceToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("DeviceToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.CyberPhisical_final.CyberPhisical_finalToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("CyberPhisical_finalToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"CreateExampleClassF1Keyword", // F1 help keyword for the toolbox item.
						resourceManager.GetString("DeviceToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.CyberPhisical_final.Device.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.CyberPhisical_final.TemperatureToolboxItem":
					// Add Temperature shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.CyberPhisical_final.TemperatureToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("TemperatureToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TemperatureToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.CyberPhisical_final.CyberPhisical_finalToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("CyberPhisical_finalToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Tempertature", // F1 help keyword for the toolbox item.
						resourceManager.GetString("TemperatureToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.CyberPhisical_final.Temperature.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.CyberPhisical_final.SirenToolboxItem":
					// Add Siren shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.CyberPhisical_final.SirenToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("SirenToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("SirenToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.CyberPhisical_final.CyberPhisical_finalToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("CyberPhisical_finalToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Siren", // F1 help keyword for the toolbox item.
						resourceManager.GetString("SirenToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.CyberPhisical_final.Siren.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.CyberPhisical_final.AirConditioningToolboxItem":
					// Add AirConditioning shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.CyberPhisical_final.AirConditioningToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AirConditioningToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AirConditioningToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.CyberPhisical_final.CyberPhisical_finalToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("CyberPhisical_finalToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"AirConditioning", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AirConditioningToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.CyberPhisical_final.AirConditioning.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.CyberPhisical_final.ControllerToolboxItem":
					// Add Controller shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.CyberPhisical_final.ControllerToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						5, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ControllerToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ControllerToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.CyberPhisical_final.CyberPhisical_finalToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("CyberPhisical_finalToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Controller", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ControllerToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.CyberPhisical_final.Controller.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.CyberPhisical_final.AlarmToolboxItem":
					// Add Alarm shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.CyberPhisical_final.AlarmToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						6, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AlarmToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AlarmToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.CyberPhisical_final.CyberPhisical_finalToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("CyberPhisical_finalToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Alarm", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AlarmToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.CyberPhisical_final.Alarms.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.CyberPhisical_final.ConnectionTool1ToolboxItem":

					// Add ConnectionTool1 connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.CyberPhisical_final.ConnectionTool1ToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						7, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ConnectionTool1ToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ConnectionTool1ToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"Company.CyberPhisical_final.CyberPhisical_finalToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("CyberPhisical_finalToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ConnectionTool1", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ConnectionTool1ToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ConnectionTool1FilterString)
						});
					break;
				case "Company.CyberPhisical_final.Custom_SensorToolboxItem":
					// Add Custom_Sensor shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.CyberPhisical_final.Custom_SensorToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						8, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("Custom_SensorToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("Custom_SensorToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.CyberPhisical_final.CyberPhisical_finalToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("CyberPhisical_finalToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Custom_Sensor", // F1 help keyword for the toolbox item.
						resourceManager.GetString("Custom_SensorToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.CyberPhisical_final.Custom_sensor.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.CyberPhisical_final.Custom_ActuatorToolboxItem":
					// Add Custom_Actuator shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.CyberPhisical_final.Custom_ActuatorToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						9, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("Custom_ActuatorToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("Custom_ActuatorToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.CyberPhisical_final.CyberPhisical_finalToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("CyberPhisical_finalToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"", // F1 help keyword for the toolbox item.
						resourceManager.GetString("Custom_ActuatorToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.CyberPhisical_final.custom_actuator.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.CyberPhisical_final.HumedityToolboxItem":
					// Add Humedity shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.CyberPhisical_final.HumedityToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						10, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("HumedityToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("HumedityToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.CyberPhisical_final.CyberPhisical_finalToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("CyberPhisical_finalToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Humedity", // F1 help keyword for the toolbox item.
						resourceManager.GetString("HumedityToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.CyberPhisical_final.Humidity.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.CyberPhisical_final.SmokeToolboxItem":
					// Add Smoke shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.CyberPhisical_final.SmokeToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						11, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("SmokeToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("SmokeToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.CyberPhisical_final.CyberPhisical_finalToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("CyberPhisical_finalToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Smoke", // F1 help keyword for the toolbox item.
						resourceManager.GetString("SmokeToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.CyberPhisical_final.SmokeSensor.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				default:
					break;
			} // end switch
			
			return result;
		}
		

		/// <summary>
		/// The store toe be used for all the toolbox item creation
		/// </summary>
		protected DslModeling::Store ToolboxStore
		{
			get
			{ 
				if (toolboxStore==null)
				{
					toolboxStore = new DslModeling::Store(this.ServiceProvider);
					EventHandler StoreCleanUp = (o, e) =>
					{
						//Since Store implements IDisposable, we need to dispose it when we're finished
						if (this.toolboxStore != null)
						{
							this.toolboxStore.Dispose();
						}
						this.toolboxStore = null;
					};
					//There is no DomainUnload event for the default AppDomain, so we listen for both ProcessExit and DomainUnload
					AppDomain.CurrentDomain.ProcessExit += new EventHandler(StoreCleanUp);
					AppDomain.CurrentDomain.DomainUnload += new EventHandler(StoreCleanUp);
					
					//load the domain model
					toolboxStore.LoadDomainModels(typeof(global::Company.CyberPhisical_final.CyberPhisical_finalDomainModel));
					
				}
				return toolboxStore;
			}
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" returns the the toolbox item using cached dictionary
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve</param>
		private DslDesign::ModelingToolboxItem GetToolboxItem(string itemId)
		{
			DslDesign::ModelingToolboxItem item = null;

			if (!this.toolboxItemCache.TryGetValue(itemId, out item))
			{
				DslModeling::Store store = this.ToolboxStore;
				
				// Open transaction so we can create model elements corresponding to toolbox items.
				using (DslModeling::Transaction t = store.TransactionManager.BeginTransaction("CreateToolboxItems"))
				{
					// Retrieve the specified ToolboxItem from the DSL
					this.toolboxItemCache[itemId] = item = this.GetToolboxItem(itemId, store);
				}
			}

			return item;
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		public virtual object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			DslDesign::ModelingToolboxItem item = null;

			global::System.Resources.ResourceManager resourceManager = global::Company.CyberPhisical_final.CyberPhisical_finalDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;

			System.Windows.Forms.IDataObject tbxDataObj;

			//get the toolbox item
			item = GetToolboxItem(itemId);

			if (item != null)
			{
				ToolboxItemContainer container = new ToolboxItemContainer(item);
				tbxDataObj = container.ToolboxData;

				if (tbxDataObj.GetDataPresent(format.Name))
				{
					return tbxDataObj.GetData(format.Name);
				}
				else 
				{
					string invalidFormatString = resourceManager.GetString("UnsupportedToolboxFormat", resourceCulture);
					throw new InvalidOperationException(string.Format(resourceCulture, invalidFormatString, format.Name));
				}
			}

			string errorFormatString = resourceManager.GetString("UnresolvedToolboxItem", resourceCulture);
			throw new InvalidOperationException(string.Format(resourceCulture, errorFormatString, itemId));
		}		
	}
}
